### ISSUE TITLE
'EnforcePriorBackward' object has no attribute 'prior'

### ISSUE THREAD

**Issue by phamquandung** [evanmy/sae#3]
Dear author,

Thank you for your great paper!

I am trying to run your code (python3 test.py 0). However, I got an error as below. 
```
 Traceback (most recent call last):
   File "test.py", line 144, in <module>
     stat, file_names = run(loader= [dataset, test_idx],
   File "test.py", line 67, in run
     out = m.enforcer(prior, out) 
   File "/vinbrain/pqdung_train/sae/functions/models.py", line 107, in enforcer
     return EnforcePrior(prior)(x)
   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/function.py", line 159, in __call__
     raise RuntimeError(
 RuntimeError: Legacy autograd function with non-static forward method is deprecated. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```
Then I tried to fix this bug by modifying your code in functions/models.py as below:

![image](https://user-images.githubusercontent.com/28943896/117421309-a115d200-af48-11eb-8ce9-078063c946e7.png)

Unfortunately, I got another error:

```
Traceback (most recent call last):
   File "test.py", line 144, in <module>
     stat, file_names = run(loader= [dataset, test_idx],
   File "test.py", line 67, in run
     out = m.enforcer(prior, out) 
   File "/vinbrain/pqdung_train/sae/functions/models.py", line 110, in enforcer
     return EnforcePrior(prior).apply(x)
   File "/vinbrain/pqdung_train/sae/functions/models.py", line 98, in forward
     self.forbidden_regs = (self.prior < self.eps).float()
 AttributeError: 'EnforcePriorBackward' object has no attribute 'prior'
```

Could you please help me to find out the problem?

Thank you in advance!

**Comment by evanmy** [comment]
Thank you for your feedback. It seems that they deprecated the old way of modifying the gradients. I need change the code to reflect the newer convention of torch. For now, you can try installing pytorch 1.1. You shouldn't encounter the deprecation notice with that version.

**Comment by phamquandung** [comment]
> Thank you for your feedback. It seems that they deprecated the old way of modifying the gradients. I need change the code to reflect the newer convention of torch. For now, you can try installing pytorch 1.1. You shouldn't encounter the deprecation notice with that version.

Thanks for your reply. I'm currently using pytorch 1.7.1 and CUDA 11.0. Re-installing other version of CUDA and pytorch seems not attractive to me. I guess it would be better if we could solve this problem with newer convention of CUDA and pytorch.

**Comment by phamquandung** [comment]
Hi @evanmy ,

I think there is a problem with class python of enforcer in functions/models.py. Finally it works! We do not need to reinstall pytorch. Please check my code in functions/models.py

![image](https://user-images.githubusercontent.com/28943896/117524748-fc979c80-afe8-11eb-92de-7702429bc7be.png)

And I also modified in test.py as follow

![image](https://user-images.githubusercontent.com/28943896/117525331-e9d29700-afeb-11eb-99ff-461331fa759e.png)

**Comment by evanmy** [comment]
Thank you for looking into it! I haven't had a chance to update the code with the new convention. I will do some testing and update the enforcer once I make sure everything behaves the same.
