### ISSUE TITLE
'AssertionError: The prior should be one-hot encoded byte' during training

### ISSUE THREAD

**Issue by PiJrSSJ** [evanmy/sae#4]
Dear author,

Thank you for your contribution! I've read your paper and I am trying to run the code _!python train.py 0 2 --compute_dice_ on Colab, however, I got an error: 

![1639254062(1)](https://user-images.githubusercontent.com/84541799/145690526-885703f8-a93e-4d28-ada3-c3473652eb85.png)

Then I made a test on the function argmax_ch, and it turned out that the data type of the output of argmax_ch is boolean not torch.unint8:

![1639254479(1)](https://user-images.githubusercontent.com/84541799/145690688-a6ce14d1-4dc0-484e-be0b-7ae0346bf589.png)

I'm a little confused, could you pleas help me fix this problem?

Thank you in advance!

**Comment by evanmy** [comment]
Hi, 

Thank you for your interest in our project! Try using version 1.1. I was able to recreate this bug if I use the newer version of PyTorch, but it does not happen with 1.1.  Some functions behavior have probably changed between different versions. 

Best,
Evan

**Comment by PiJrSSJ** [comment]
Hi Evan,

Thank you very much! I rolled it back to version 1.1 and it starts to run, thanks!
